FROM elixir:1.9.4

LABEL Burgy Benjamin aka MiniDfx

# Ignore any console dialogs
ENV DEBIAN_FRONTEND=noninteractive

ENV MIX_ENV=dev

RUN mkdir /app && \
    curl -sL https://deb.nodesource.com/setup_12.x | bash - && \
    apt-get update && \
    apt-get install -y nodejs \
                       gcc\
                       make\
                       libtool-bin\
                       libgraphicsmagick1-dev\
                       tesseract-ocr\
                       tesseract-ocr-eng\
                       tesseract-ocr-fra\
                       ghostscript\
                       ghostscript-x\
                       libgs-dev\
                       xpdf\
		                   graphicsmagick && \
    npm install --unsafe-perm -g elm && \
    npm install -g brunch

WORKDIR /app

RUN mix local.hex --force && \
    mix local.rebar --force

EXPOSE 4000
