version: '3'

services:
  db:
    image: postgres:11.11
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=my-suPer-pa$$word
  dms42:
    image: minidfx/dms42:alpha
    depends_on:
      - db
    ports:
      - "0.0.0.0.:4001:4001/tcp"
    environment:
      - DB_USER=postgres
      - DB_PASS=my-suPer-pa$$word
      - DB_HOST=db
      - DB_NAME=dms42-transient
      - PUID=1000
      - GUID=100
      - STOP_WORDS=au aux ce avec ces dans de des du elle en et eux il je la le leur lui ma mais me meme mes moi mon ne nos notre nous on ou par pas pour qu que qui sa se ses son sur ta te tes toi ton tu un une vos votre vous