FROM elixir

LABEL Burgy Benjamin aka MiniDfx

# Ignore any console dialogs
ENV DEBIAN_FRONTEND=noninteractive

ENV MIX_ENV=dev

RUN mkdir /app && \
    curl -sL https://deb.nodesource.com/setup_9.x | bash - && \
    apt-get update && \
    apt-get install -y gcc\
                       make\
                       libtool-bin\
                       libgraphicsmagick1-dev\
                       tesseract-ocr\
                       tesseract-ocr-eng\
                       tesseract-ocr-fra\
                       ghostscript\
                       ghostscript-x\
                       libgs-dev\
                       xpdf\
		       graphicsmagick\
    		       postgresql-client

COPY mix.exs mix.lock /app/
COPY lib /app/lib/
COPY config /app/config/
COPY priv /app/priv/
COPY wait-for-postgres.sh /app/

WORKDIR /app

RUN mix local.hex --force && \
    mix local.rebar --force && \
    mix deps.get && \
    mix deps.compile && \
    mix compile

ENTRYPOINT /app/wait-for-postgres.sh postgres &&\
	   mix app.reset &&\
	   mix phx.server

EXPOSE 4000
